# Generated by Django 3.2.5 on 2021-07-27 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210720_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoty',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='blog.categoty', verbose_name='عبارت زیر دسته'),
        ),
    ]
