# Generated by Django 3.2.5 on 2021-07-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_categoty_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoty',
            options={'ordering': ['parent__id', 'position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
